[package]
name = "sf-api"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A simple API to send commands to the Shakes & Fidget servers and parse their responses into characters"
repository = "https://github.com/the-marenga/sf-api"
readme = "README.md"

[dependencies]
aho-corasick = "1.1"
base64 = "0.22"
cbindgen = "0.24"
chrono = "0.4"
enum-map = "2.7"
fastrand = "2.2"
libaes = "0.7"
log = "0.4"
num-bigint = "0.4"
num-derive = "0.4"
num-traits = "0.2"
once_cell = "1.20"
ouroboros = "0.18"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.12", features = ["gzip", "deflate"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
sha1 = "0.10"
strum = { version = "0.26", features = ["strum_macros", "derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"], optional = true }
url = { version = "2.5", optional = true }

[features]
default = ["sso", "serde"]
session = ["dep:reqwest", "dep:tokio", "dep:url"]
sso = ["session", "dep:serde", "dep:serde_json"]
serde = ["dep:serde", "num-bigint/serde", "chrono/serde", "enum-map/serde"]

[dev-dependencies]
tokio = { version = "1.41", features = ["full"] }
env_logger = "0.11.5"

[build-dependencies]
cbindgen = "0.24"
tokio = "1.41"

[lib]
crate-type = ["staticlib"]
